# Prof. Michael A. Casey
# Dartmouth College, Department of Music, Department of Computer Science
# Course: Music and AI, 2023. Language: Sonic PI / Ruby
# Generate a contra-motion bass line from a given melody
#
# Melody given in scale degrees (0..7*num_octaves)
# a scale is a list of pitches indexed by degrees d
# the bass line is the melody inverted -d (upside-down)
#
# CS 89/189 MUS 14 "Music and AI"
# Prof. Michael Casey
# Dartmouth College, Department of Computer Science


# Melody is a list of scale degrees
mel = [0,1,2,1,2,3,2,3,4,3,4,5,4]

# Make a list of scale notes
scl = scale(:c5, :minor, num_octaves: 1)

# Play a melody
# Generate a bass by inverting and transposing
# melody (in scale degrees), d looks up the scale: scl[d]
# bass generated by inversion of the melody: scl[-d]
mel.each do |d|
  use_octave 0  # no transpose for melody
  play scl[d], amp: 0.4     # melody
  use_octave -2 # transpose -2 octaves for bass
  play scl[-d], amp: 0.4 # bass (inversion)
  sleep 0.5
end

